# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJzaSnHM4jwVfiEhyD8Nk5ovEJp5CUvl
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
import joblib

df = pd.read_csv("device_training_data.csv")
df.head()

X = df[["temperature", "humidity", "soil_moisture", "light"]]

# ======= 1. PUMP SWITCH =======
pump_clf = RandomForestClassifier(n_estimators=200, random_state=42)
pump_clf.fit(X, df["pump"])
joblib.dump(pump_clf, "pump_switch.pkl")


# ======= 2. PUMP POWER =======
pump_power_reg = RandomForestRegressor(n_estimators=200, random_state=42)
pump_power_reg.fit(X, df["pump_power"])
joblib.dump(pump_power_reg, "pump_power.pkl")


# ======= 3. PUMP DURATION (new) =======
pump_duration_reg = RandomForestRegressor(n_estimators=200, random_state=42)
pump_duration_reg.fit(X, df["pump_duration"])
joblib.dump(pump_duration_reg, "pump_duration.pkl")


# ======= 4. LIGHT SWITCH =======
light_switch_clf = RandomForestClassifier(n_estimators=200, random_state=42)
light_switch_clf.fit(X, df["light_switch"])
joblib.dump(light_switch_clf, "light_switch.pkl")


# ======= 5. LIGHT POWER =======
light_power_reg = RandomForestRegressor(n_estimators=200, random_state=42)
light_power_reg.fit(X, df["light_power"])
joblib.dump(light_power_reg, "light_power.pkl")


# ======= 6. LIGHT DURATION (new) =======
light_duration_reg = RandomForestRegressor(n_estimators=200, random_state=42)
light_duration_reg.fit(X, df["light_duration"])
joblib.dump(light_duration_reg, "light_duration.pkl")

# ============= TEST SAMPLE =============
sample = pd.DataFrame([{
    "temperature": 90,
    "humidity": 55,
    "soil_moisture": 20,
    "light": 500
}])

pump_pred = pump_clf.predict(sample)[0]
pump_power = pump_power_reg.predict(sample)[0]
pump_duration = pump_duration_reg.predict(sample)[0]

light_pred = light_switch_clf.predict(sample)[0]
light_power = light_power_reg.predict(sample)[0]
light_duration = light_duration_reg.predict(sample)[0]

print("Pump:", pump_pred)
print("Pump Power:", round(pump_power, 2))
print("Pump Duration:", round(pump_duration, 2))

print("Light:", light_pred)
print("Light Power:", round(light_power, 2))
print("Light Duration:", round(light_duration, 2))